### ISSUE TITLE
Heroku crash

### ISSUE THREAD

**Issue by muhammadsamir11** [dmytrostriletskyi/heroku-load-balancer#12]
Process exited with status 1
2021-09-02T15:37:48.338258+00:00 app[web.1]: Traceback (most recent call last):
2021-09-02T15:37:48.338267+00:00 app[web.1]:   File "src/entrypoint.py", line 61, in <module>
2021-09-02T15:37:48.338268+00:00 app[web.1]:     cli()
2021-09-02T15:37:48.338268+00:00 app[web.1]:   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
2021-09-02T15:37:48.338268+00:00 app[web.1]:     return self.main(*args, **kwargs)
2021-09-02T15:37:48.338269+00:00 app[web.1]:   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
2021-09-02T15:37:48.338269+00:00 app[web.1]:     rv = self.invoke(ctx)
2021-09-02T15:37:48.338269+00:00 app[web.1]:   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
2021-09-02T15:37:48.338270+00:00 app[web.1]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
2021-09-02T15:37:48.338270+00:00 app[web.1]:   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
2021-09-02T15:37:48.338270+00:00 app[web.1]:     return ctx.invoke(self.callback, **ctx.params)
2021-09-02T15:37:48.338270+00:00 app[web.1]:   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
2021-09-02T15:37:48.338270+00:00 app[web.1]:     return callback(*args, **kwargs)
2021-09-02T15:37:48.338271+00:00 app[web.1]:   File "src/entrypoint.py", line 53, in create_load_balancer
2021-09-02T15:37:48.338271+00:00 app[web.1]:     identifier=pipeline_identifier,
2021-09-02T15:37:48.338271+00:00 app[web.1]:   File "/heroku-load-balancer/src/heroku.py", line 62, in by_pipeline_identifier
2021-09-02T15:37:48.338271+00:00 app[web.1]:     if application.get('stage') == 'production':
2021-09-02T15:37:48.338272+00:00 app[web.1]: AttributeError: 'str' object has no attribute 'get'

**Comment by dmytrostriletskyi** [comment]
@muhammadsamir11, hi, thank you for you issue. This may happen when you specify wrong pipeline identifier. Are you sure you specified the right one? 

Example of it is on the screenshot:

![image](https://user-images.githubusercontent.com/22666467/132012788-71fc4959-9e6e-412e-b41d-a98ef1260218.png)

**Comment by muhammadsamir11** [comment]
Yes I am sure I define the right id for the pipeline even I tried to set up a new dyno for load balancer and still getting same problem, Thanks a lot for your reply

**Comment by muhammadsamir11** [comment]
Thanks a lot, I found the issue it was the apikey change automatically after I change the password
